### PR TITLE
Add extra fix for PermissionError

### PR DESCRIPTION
**Pull request by SiboVG**
I was just testing the TMC lib on my RPi model 4B (I previously used an RPi 3) and got the `PermissionError: [Errno 13]
Permission denied: '/dev/serial0'` error. The mentioned fix in the README did not work for me. I had to give serial0 read/write access by calling `sudo chmod 666 /dev/serial0`. This PR updates the README with that info.

### CODE REVIEW

**Comment by Chr157i4n** [comment]
can you check the following things on your RPi:

`ls -lha /dev/serial0`
On my RPi this shows a link to the file ttyS0:
`lrwxrwxrwx 1 root root 5 Apr 13 00:00 /dev/serial0 -> ttyS0`

`ls -lha /dev/ttyS0`
This shows that the "file" ttyS0 is owned by the group dialout with read/write access
`crw-rw---- 1 root dialout 4, 64 Apr 13 00:00 /dev/ttyS0`

**Comment by SiboVG** [comment]
> can you check the following things on your RPi:
> 
> `ls -lha /dev/serial0` On my RPi this shows a link to the file ttyS0: `lrwxrwxrwx 1 root root 5 Apr 13 00:00 /dev/serial0 -> ttyS0`
> 
> `ls -lha /dev/ttyS0` This shows that the "file" ttyS0 is owned by the group dialout with read/write access `crw-rw---- 1 root dialout 4, 64 Apr 13 00:00 /dev/ttyS0`

I have the same outputs. Do note that this is the output after I ran the `chmod` command, it may have been different before I called `chmod`.

**Comment by Chr157i4n** [comment]
does `sudo chmod 660 /dev/serial0` work for you aswell?

**Comment by SiboVG** [comment]
> does `sudo chmod 660 /dev/serial0` work for you aswell?

It does.

**Comment by Chr157i4n** [comment]
have you logged out and back in on the RPi after adding your user to the dialout group?

**Comment by SiboVG** [comment]
> have you logged out and back in on the RPi after adding your user to the dialout group?

I rebooted the system.

**Pull request merged**
